# Image 

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy 

In [3]:
numpy.__version__

'1.21.5'

In [4]:
pip install --upgrade opencv-python

  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.9.0.80
    Uninstalling opencv-python-4.9.0.80:
      Successfully uninstalled opencv-python-4.9.0.80
Note: you may need to restart the kernel to use updated packages.


In [5]:
import cv2

check the version

In [6]:
pip install --upgrade numpy

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 2.0.1 which is incompatible.
scikit-learn 1.4.1.post1 requires numpy<2.0,>=1.19.5, but you have numpy 2.0.1 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 2.0.1 which is incompatible.



  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5


# Reading image

In [7]:
import cv2

In [8]:
import numpy as np

In [15]:
img=cv2.imread('Leo1.jpg')

In [16]:
print(img)

[[[211 228 225]
  [210 227 224]
  [210 227 224]
  ...
  [ 43  71  78]
  [ 34  62  69]
  [ 35  63  70]]

 [[211 228 225]
  [210 227 224]
  [210 227 224]
  ...
  [ 42  70  77]
  [ 40  68  75]
  [ 44  72  79]]

 [[211 228 225]
  [211 228 225]
  [210 227 224]
  ...
  [ 46  74  81]
  [ 45  73  80]
  [ 48  76  83]]

 ...

 [[190 194 195]
  [191 195 196]
  [192 196 197]
  ...
  [ 10  38  55]
  [ 11  39  56]
  [ 12  40  57]]

 [[190 194 195]
  [190 194 195]
  [190 194 195]
  ...
  [ 11  39  56]
  [ 11  39  56]
  [ 10  38  55]]

 [[190 194 195]
  [189 193 194]
  [188 192 193]
  ...
  [ 11  39  56]
  [  8  36  53]
  [  5  33  50]]]


In [17]:
color_avl=[i for i in dir(cv2) if i.startswith("COLOR_BGR")]

In [18]:
print(color_avl)

['COLOR_BGR2BGR555', 'COLOR_BGR2BGR565', 'COLOR_BGR2BGRA', 'COLOR_BGR2GRAY', 'COLOR_BGR2HLS', 'COLOR_BGR2HLS_FULL', 'COLOR_BGR2HSV', 'COLOR_BGR2HSV_FULL', 'COLOR_BGR2LAB', 'COLOR_BGR2LUV', 'COLOR_BGR2Lab', 'COLOR_BGR2Luv', 'COLOR_BGR2RGB', 'COLOR_BGR2RGBA', 'COLOR_BGR2XYZ', 'COLOR_BGR2YCR_CB', 'COLOR_BGR2YCrCb', 'COLOR_BGR2YUV', 'COLOR_BGR2YUV_I420', 'COLOR_BGR2YUV_IYUV', 'COLOR_BGR2YUV_UYNV', 'COLOR_BGR2YUV_UYVY', 'COLOR_BGR2YUV_Y422', 'COLOR_BGR2YUV_YUNV', 'COLOR_BGR2YUV_YUY2', 'COLOR_BGR2YUV_YUYV', 'COLOR_BGR2YUV_YV12', 'COLOR_BGR2YUV_YVYU', 'COLOR_BGR5552BGR', 'COLOR_BGR5552BGRA', 'COLOR_BGR5552GRAY', 'COLOR_BGR5552RGB', 'COLOR_BGR5552RGBA', 'COLOR_BGR5652BGR', 'COLOR_BGR5652BGRA', 'COLOR_BGR5652GRAY', 'COLOR_BGR5652RGB', 'COLOR_BGR5652RGBA', 'COLOR_BGRA2BGR', 'COLOR_BGRA2BGR555', 'COLOR_BGRA2BGR565', 'COLOR_BGRA2GRAY', 'COLOR_BGRA2RGB', 'COLOR_BGRA2RGBA', 'COLOR_BGRA2YUV_I420', 'COLOR_BGRA2YUV_IYUV', 'COLOR_BGRA2YUV_UYNV', 'COLOR_BGRA2YUV_UYVY', 'COLOR_BGRA2YUV_Y422', 'COLOR_BGRA2

In [22]:
img =cv2.imread( "Leo1.jpg" )

In [23]:
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
hsv =cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
rgb =cv2.cvtColor(img,cv2.COLOR_BGR2RGB)