In [1]:
import cv2
import numpy as np

# Reading Image

In [2]:
img = cv2.imread('Leo1.jpeg')

# Displaing the read image

In [3]:
cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Shape of an image

In [4]:
shp = img.shape
shp

(1280, 675, 3)

# reshape imag

In [6]:
reshape_image = cv2.resize(img,(500,500))

In [7]:
reshape_image.shape

(500, 500, 3)

In [8]:
cv2.imshow("Image", img)
cv2.imshow("Resize Image",reshape_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# value of Pixel

In [9]:
px =img[201,200]
px

array([0, 0, 0], dtype=uint8)

In [10]:
img = cv2.imread('Leo1.jpeg')

In [11]:
#select ROI
r = cv2.selectROI("Select the area",img)

# Crop image
cropped_image = img[int(r[1]):int(r[1]+r[3]),int(r[0]):int(r[0]+r[2])]

cv2.imshow("Cropped Image",cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
cropped_image

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[230, 235, 234],
        [223, 228, 227],
        [223, 228, 227],
        ...,
        [ 32,  43,  75],
        [ 31,  42,  74],
        [ 29,  39,  69]],

       [[230, 235, 234],
        [222, 227, 226],
        [221, 226, 225],
        ...,
        [ 32,  42,  76],
        [ 31,  42,  72],
        [ 29,  39,  69]],

       [[229, 234, 233],
        [221, 226, 225],
        [218, 223, 222],
        ...,
        [ 32,  42,  76],
        [ 31,  42,  72],
        [ 29,  39,  69]]

# save Cropped image

In [16]:
cv2.imsave('Leo1.jpeg',cropped_image)

AttributeError: module 'cv2' has no attribute 'imsave'

In [15]:
cv2.imwrite("SaveImage1.jpeg",cropped_image)

True


# splitting image

In [17]:
img = cv2.imread('Leo1.jpeg')
img

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,

       [[43, 43, 43],
        [43, 43, 43],
        [43, 43, 43],
        ...,
        [47, 47, 47],
        [47, 47, 47],
        [46, 46, 46]],

       [[67, 67, 67],
        [68, 68, 68],
        [68, 68, 68],
        ...,
        [54, 54, 54],
        [53, 53, 53],
        [53, 53, 53]],

       [[69, 69, 69],
        [69, 69, 69],
        [70, 70, 70],
        ...,
        [59, 59, 59],
        [59, 59, 59],
        [58, 58, 58]]], dtype=uint8)

In [18]:
b,g,r  = cv2.split(img)

cv2.imshow('image',img)
cv2.imshow("blue",b)
cv2.imshow("green",g)
cv2.imshow("red",r)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Merging an image